# Generated by Django 4.2.3 on 2023-07-14 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_control', '0003_product_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='creator',
        ),
        migrations.AlterField(
            model_name='product',
            name='Entered_By',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
