# Generated by Django 4.2.2 on 2023-07-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0006_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
