# Generated by Django 4.2.2 on 2023-07-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0009_visit_order_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.product'),
        ),
    ]
