# Generated by Django 4.2.2 on 2023-07-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0010_alter_deal_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
