# Generated by Django 4.2.2 on 2023-07-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0012_deal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
