# Generated by Django 4.2.3 on 2023-07-22 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0013_delete_order_delete_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='quantity_ordered',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
