# Generated by Django 4.2.3 on 2023-07-22 08:34

import admin_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0016_alter_doctor_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.IntegerField(validators=[admin_control.models.validate_contact_number]),
        ),
    ]
