# Generated by Django 4.2.3 on 2023-07-22 08:45

import admin_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0017_alter_doctor_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(validators=[admin_control.models.future_date_validator]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(validators=[admin_control.models.future_date_validator]),
        ),
    ]
