# Generated by Django 4.2.3 on 2023-07-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0019_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
