# Generated by Django 4.2.3 on 2023-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0021_alter_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoinmentstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_failed', models.BooleanField(default=False)),
            ],
        ),
    ]
